spring:
  application:
    name: taco-cloud
  datasource:
    generate-unique-name: false
    name: tacocloud
  thymeleaf:
    cache: false
  cassandra:
    keyspace-name: tacocloud
    schema-action: recreate
    local-datacenter: datacenter1
